#!/bin/bash

function is_server_installed {
	case $1 in
		"passenger") 
			;;
		"puma")
			gem_exists "$1"
			;;
		*)
			echo "WARN: Unknown \"$1\" server" >&2
			exit 1
			;;
	esac
}

function gem_exists() {
	[ "`gem list -i $1`" == "true" ]
}
