#!/bin/bash
source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"


function is_server_installed {
	case $1 in
		"passenger") 
			;;
		"puma"|"thin")
			gem_exists "$1"
			;;
		*)
			echo "WARN: Unknown \"$1\" server" >&2
			exit 1
			;;
	esac
}

function gem_exists() {
	[ "`gem list -i $1`" == "true" ]
}

function run_command() {
	if [ -f ${OPENSHIFT_REPO_DIR}/Gemfile ]
	then
		ruby_context 'bundle exec "$1"'
	else
		ruby_context '$1'
	fi

}
