#!/bin/bash -e

ensure_valid_httpd_process "$HTTPD_PID_FILE" "$HTTPD_CFG_FILE"
if [ -f "$HTTPD_PID_FILE" ]; then
	httpd_pid=`cat "$HTTPD_PID_FILE" 2> /dev/null`
fi
ruby_context "/usr/sbin/httpd -C 'Include $OPENSHIFT_RUBY_DIR/etc/conf.d/*.conf' -f $HTTPD_CFG_FILE -k stop"
wait_for_stop $httpd_pid